# version: '3.5'

# services:
#   sample-app:
#     container_name: tech-voting
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - '.:/usr/src/app'
#       - '/usr/src/app/node_modules'
#     ports:
#       - '3000:3000'
